import type { Product, Category } from "./types";

export const VOLTEC_WHATSAPP = "971525414894";

// Pre-filled WhatsApp inquiry text — reads like a message the customer would
// actually type. Keep it to one natural line; just carry the product name so
// the lead is self-identifying (never a bare "10kw stabilizer" — we sell SVC,
// IGBT and SCR 10kVA plus a 10,000W AC unit, so the model name matters).
export function whatsappLink(productName?: string): string {
  const text = productName
    ? `Hi Voltec! I want to inquire about ${productName}.`
    : "Hi Voltec! I want to inquire about your voltage stabilizers.";
  return `https://wa.me/${VOLTEC_WHATSAPP}?text=${encodeURIComponent(text)}`;
}

// Voltec sells electrical PRODUCTS across Pakistan — voltage stabilizers (IGBT,
// SVC, AVR), industrial stabilizers, lithium cells, and supporting electronics.
export const PRODUCTS: Product[] = [
  // ===== INVERTER (IGBT) STABILIZERS — ADA series, 6 models =====
  // Specs from the factory data sheet (ADA-A series). Same engineering across
  // the range; capacity, current, no-load loss, size and weight vary per model.
  {
    id: "vt-igbt-550",
    name: "IGBT Inverter Stabilizer — 550VA",
    category: "Voltage Stabilizers",
    categoryId: "stabilizers",
    tech: "IGBT",
    showcase: "stabilizer",
    status: "upcoming",
    tagline: "A small inverter stabilizer for a TV, router and lights.",
    useFor: "Sensitive electronics & instruments",
    highlight: ["550VA", "plug & play"],
    description:
      "A small inverter stabilizer for a TV, router and a few lights. It fixes voltage instantly (0 ms) with no moving parts. The wide 90–310V input holds a steady 220V even when the voltage drops. Pure sine output, ≥96% efficient.",
    image: "assets/igbt/display.jpg",
    specs: [
      ["Technology", "IGBT inverter (no moving parts)"],
      ["Capacity", "550VA, single-phase"],
      ["Rated current", "2.5A"],
      ["Input range", "90V – 310V AC"],
      ["Output", "220V / 230V"],
      ["Output accuracy", "±2%"],
      ["Response time", "0 ms"],
      ["Waveform", "Pure sine (THD < 3%)"],
      ["Efficiency", "≥ 96%"],
      ["No-load loss", "10W"],
    ],
    packing: { productSize: "23 × 17 × 8.85 cm", packSize: "49 × 29.5 × 24.5 cm", nw: "2.1 kg", gw: "2.4 kg" },
  },
  {
    id: "vt-igbt-2k",
    name: "IGBT Inverter Stabilizer — 2kVA",
    category: "Voltage Stabilizers",
    categoryId: "stabilizers",
    tech: "IGBT",
    showcase: "stabilizer",
    status: "upcoming",
    tagline: "For one AC or a room full of electronics.",
    useFor: "Lab, medical & office equipment",
    highlight: ["2kVA", "0 ms"],
    description:
      "For a single AC or a room of electronics. It corrects voltage instantly (0 ms) with no servo motor and no brushes. The wide 90–310V input holds 220V through sags and surges. Pure sine, ≥96% efficient and silent.",
    image: "assets/igbt/display.jpg",
    specs: [
      ["Technology", "IGBT inverter (no moving parts)"],
      ["Capacity", "2kVA, single-phase"],
      ["Rated current", "10A"],
      ["Input range", "90V – 310V AC"],
      ["Output", "220V / 230V"],
      ["Output accuracy", "±2%"],
      ["Response time", "0 ms"],
      ["Waveform", "Pure sine (THD < 3%)"],
      ["Efficiency", "≥ 96%"],
      ["No-load loss", "19W"],
    ],
    packing: { productSize: "27.8 × 20.5 × 10.17 cm", packSize: "56 × 34.5 × 27 cm", nw: "3.3 kg", gw: "3.6 kg" },
  },
  {
    id: "vt-igbt-5k",
    name: "IGBT Inverter Stabilizer — 5kVA",
    category: "Voltage Stabilizers",
    categoryId: "stabilizers",
    tech: "IGBT",
    showcase: "stabilizer",
    status: "upcoming",
    tagline: "For a small home — one or two ACs plus the basics.",
    useFor: "Clinics, small laser & CNC",
    highlight: ["5kVA", "pure sine"],
    description:
      "For a small home — one or two ACs plus fridge, fans and electronics. Instant inverter correction, no moving parts, ≥96% efficient. Pure sine output keeps sensitive appliances safe.",
    image: "assets/igbt/display.jpg",
    specs: [
      ["Technology", "IGBT inverter (no moving parts)"],
      ["Capacity", "5kVA, single-phase"],
      ["Rated current", "25A"],
      ["Input range", "90V – 310V AC"],
      ["Output", "220V / 230V"],
      ["Output accuracy", "±2%"],
      ["Response time", "0 ms"],
      ["Waveform", "Pure sine (THD < 3%)"],
      ["Efficiency", "≥ 96%"],
      ["No-load loss", "31W"],
    ],
    packing: { productSize: "37 × 29 × 12.2 cm", packSize: "43 × 34 × 16 cm", nw: "7.3 kg", gw: "8 kg" },
  },
  {
    id: "vt-igbt-10k",
    name: "IGBT Inverter Stabilizer — 10kVA",
    category: "Voltage Stabilizers",
    categoryId: "stabilizers",
    tech: "IGBT",
    badge: "Flagship",
    showcase: "stabilizer",
    status: "upcoming",
    tagline: "Covers a full home on clean, steady power.",
    useFor: "Laser & CNC machines",
    highlight: ["10kVA", "whole home"],
    description:
      "Covers a full home — many ACs, motors and electronics — on clean, steady 220V. Instant 0 ms inverter correction with no servo motor to service. Wide 90–310V input, pure sine output, ≥96% efficient.",
    image: "assets/igbt/display.jpg",
    specs: [
      ["Technology", "IGBT inverter (no moving parts)"],
      ["Capacity", "10kVA, single-phase"],
      ["Rated current", "50A"],
      ["Input range", "90V – 310V AC"],
      ["Output", "220V / 230V"],
      ["Output accuracy", "±2%"],
      ["Response time", "0 ms"],
      ["Waveform", "Pure sine (THD < 3%)"],
      ["Efficiency", "≥ 96%"],
      ["No-load loss", "65W"],
    ],
    packing: { productSize: "50 × 39 × 14.2 cm", packSize: "56 × 44 × 18.5 cm", nw: "12.7 kg", gw: "13.7 kg" },
  },
  {
    id: "vt-igbt-15k",
    name: "IGBT Inverter Stabilizer — 15kVA",
    category: "Voltage Stabilizers",
    categoryId: "stabilizers",
    tech: "IGBT",
    showcase: "stabilizer",
    status: "upcoming",
    tagline: "Whole-home and small-shop power.",
    useFor: "Large laser & production lines",
    highlight: ["15kVA", "0 ms"],
    description:
      "Whole-home and small-shop power — geysers, ACs, motors and electronics. Instant inverter correction, no moving parts, ≥96% efficient. Holds 220V through deep voltage drops.",
    image: "assets/igbt/display.jpg",
    specs: [
      ["Technology", "IGBT inverter (no moving parts)"],
      ["Capacity", "15kVA, single-phase"],
      ["Rated current", "75A"],
      ["Input range", "90V – 310V AC"],
      ["Output", "220V / 230V"],
      ["Output accuracy", "±2%"],
      ["Response time", "0 ms"],
      ["Waveform", "Pure sine (THD < 3%)"],
      ["Efficiency", "≥ 96%"],
      ["No-load loss", "75W"],
    ],
    packing: { productSize: "50 × 41 × 21.2 cm", packSize: "56 × 46 × 25.5 cm", nw: "19.5 kg", gw: "22 kg" },
  },
  {
    id: "vt-igbt-20k",
    name: "IGBT Inverter Stabilizer — 20kVA",
    category: "Voltage Stabilizers",
    categoryId: "stabilizers",
    tech: "IGBT",
    showcase: "stabilizer",
    status: "upcoming",
    tagline: "Large home or shop load on clean, steady power.",
    useFor: "Heavy precision machinery",
    highlight: ["20kVA", "≥96%"],
    description:
      "A large home or shop load on clean, steady power. Instant 0 ms inverter correction, sealed and silent, ≥96% efficient. The wide 90–310V input rides through the worst sags and surges.",
    image: "assets/igbt/display.jpg",
    specs: [
      ["Technology", "IGBT inverter (no moving parts)"],
      ["Capacity", "20kVA, single-phase"],
      ["Rated current", "100A"],
      ["Input range", "90V – 310V AC"],
      ["Output", "220V / 230V"],
      ["Output accuracy", "±2%"],
      ["Response time", "0 ms"],
      ["Waveform", "Pure sine (THD < 3%)"],
      ["Efficiency", "≥ 96%"],
      ["No-load loss", "85W"],
    ],
    packing: { productSize: "50 × 41 × 21.2 cm", packSize: "56 × 46 × 25.5 cm", nw: "22 kg", gw: "23.2 kg" },
  },

  // ===== SCR (THYRISTOR) STABILIZERS — ITK series, solid-state, stepped =====
  // Positioning: solid-state SPEED to protect tier-1 sensitive equipment like
  // laser machines (no motor/brush), stepped ±5% correction. NEVER "stepless /
  // pure sine / ±1% / precision" — those stay reserved for the inverter (IGBT)
  // range. Specs from the ITK catalogue.
  {
    id: "vt-scr-1k",
    name: "SCR Thyristor Stabilizer — 1kVA",
    category: "Voltage Stabilizers",
    categoryId: "stabilizers",
    tech: "SCR",
    tagline: "Solid-state protection for sensitive electronics — no motor, no brushes.",
    useFor: "Sensitive electronics & instruments",
    highlight: ["1kVA", "solid-state"],
    description:
      "Solid-state thyristor (SCR) switching corrects voltage faster than a servo, with no motor and no carbon brush to wear out. Correction is stepped and holds 220V ±5% across a wide 95–250V input — built to protect sensitive electronics with solid-state speed — no motor or brush to wear out.",
    image: "assets/scr/itk-unit.jpg",
    specs: [
      ["Technology", "SCR thyristor (solid-state, no moving parts)"],
      ["Capacity", "1kVA, single-phase"],
      ["Input range", "95V – 250V AC (works 85–268V)"],
      ["Output", "220V ±5%, 50/60Hz"],
      ["Correction", "Stepped, ~20 ms response"],
      ["Efficiency", "≥ 95%"],
      ["Protection", "Over/under-voltage, overload, over-temp, short-circuit"],
      ["Restart delay", "Short 5s / Long 200s"],
    ],
    packing: { productSize: "32.3 × 26.8 × 11.6 cm", packSize: "40.5 × 32 × 17.5 cm", nw: "6.4 kg", gw: "6.8 kg" },
  },
  {
    id: "vt-scr-2k",
    name: "SCR Thyristor Stabilizer — 2kVA",
    category: "Voltage Stabilizers",
    categoryId: "stabilizers",
    tech: "SCR",
    tagline: "Fast, silent, spark-free — built to protect sensitive electronics.",
    useFor: "Sensitive electronics & small clinical devices",
    highlight: ["2kVA", "spark-free"],
    description:
      "A solid-state thyristor stabilizer that switches silently and spark-free — nothing mechanical to wear out. It corrects in steps, fast, holding 220V ±5% across a wide 95–250V input. The right pick for sensitive electronics and small clinical devices that need reliable, low-maintenance protection.",
    image: "assets/scr/itk-unit.jpg",
    specs: [
      ["Technology", "SCR thyristor (solid-state, no moving parts)"],
      ["Capacity", "2kVA, single-phase"],
      ["Input range", "95V – 250V AC (works 85–268V)"],
      ["Output", "220V ±5%, 50/60Hz"],
      ["Correction", "Stepped, ~20 ms response"],
      ["Efficiency", "≥ 95%"],
      ["Protection", "Over/under-voltage, overload, over-temp, short-circuit"],
      ["Restart delay", "Short 5s / Long 200s"],
    ],
    packing: { productSize: "32.3 × 26.8 × 11.6 cm", packSize: "40.5 × 32 × 17.5 cm", nw: "7.5 kg", gw: "8.3 kg" },
  },
  {
    id: "vt-scr-3k",
    name: "SCR Thyristor Stabilizer — 3kVA",
    category: "Voltage Stabilizers",
    categoryId: "stabilizers",
    tech: "SCR",
    tagline: "Solid-state speed for a laser or clinical machine.",
    useFor: "Lasers, ultrasound & clinical equipment",
    highlight: ["3kVA", "no moving parts"],
    description:
      "Solid-state SCR switching gives this 3kVA stabilizer faster response than a servo with nothing mechanical to service — no motor, no brush. Stepped correction holds 220V ±5% across a wide input, with six layers of protection. Ideal for laser machines, ultrasound and clinical equipment that need fast, solid-state protection.",
    image: "assets/scr/itk-unit.jpg",
    specs: [
      ["Technology", "SCR thyristor (solid-state, no moving parts)"],
      ["Capacity", "3kVA, single-phase"],
      ["Input range", "95V – 250V AC (works 85–268V)"],
      ["Output", "220V ±5%, 50/60Hz"],
      ["Correction", "Stepped, ~20 ms response"],
      ["Efficiency", "≥ 95%"],
      ["Protection", "Over/under-voltage, overload, over-temp, short-circuit"],
      ["Restart delay", "Short 5s / Long 200s"],
    ],
    packing: { productSize: "36.3 × 26.8 × 14.5 cm", packSize: "43.3 × 33.5 × 19 cm", nw: "12 kg", gw: "12.5 kg" },
  },
  {
    id: "vt-scr-5k",
    name: "SCR Thyristor Stabilizer — 5kVA",
    category: "Voltage Stabilizers",
    categoryId: "stabilizers",
    tech: "SCR",
    tagline: "Solid-state protection for tier-1 sensitive equipment.",
    useFor: "Laser machines & sensitive clinical equipment",
    highlight: ["5kVA", "long lifespan"],
    description:
      "A 5kVA solid-state thyristor stabilizer for a home or shop — faster than a servo, with no motor or brush to wear out, so the protection itself lasts. Stepped correction holds 220V ±5% over a wide 95–250V input. Built to protect tier-1 sensitive equipment like laser machines, where solid-state speed and longevity matter most.",
    image: "assets/scr/itk-unit.jpg",
    specs: [
      ["Technology", "SCR thyristor (solid-state, no moving parts)"],
      ["Capacity", "5kVA, single-phase"],
      ["Input range", "95V – 250V AC (works 85–268V)"],
      ["Output", "220V ±5%, 50/60Hz"],
      ["Correction", "Stepped, ~20 ms response"],
      ["Efficiency", "≥ 95%"],
      ["Protection", "Over/under-voltage, overload, over-temp, short-circuit"],
      ["Restart delay", "Short 5s / Long 200s"],
    ],
    packing: { productSize: "43.8 × 33.5 × 16.5 cm", packSize: "49 × 40.5 × 21 cm", nw: "18.4 kg", gw: "19.3 kg" },
  },
  {
    id: "vt-scr-10k",
    name: "SCR Thyristor Stabilizer — 10kVA",
    category: "Voltage Stabilizers",
    categoryId: "stabilizers",
    tech: "SCR",
    tagline: "Solid-state protection for larger laser & clinical equipment.",
    useFor: "Larger laser & clinical equipment",
    highlight: ["10kVA", "solid-state"],
    description:
      "The largest single-phase SCR thyristor unit — 10kVA of solid-state, spark-free correction for larger laser machines and clinical equipment. It switches faster than a servo and has no motor or carbon brush to wear out. Stepped correction holds 220V ±5% across a wide input, with six layers of protection.",
    image: "assets/scr/itk-unit.jpg",
    specs: [
      ["Technology", "SCR thyristor (solid-state, no moving parts)"],
      ["Capacity", "10kVA, single-phase"],
      ["Input range", "95V – 250V AC (works 85–268V)"],
      ["Output", "220V ±5%, 50/60Hz"],
      ["Correction", "Stepped, ~20 ms response"],
      ["Efficiency", "≥ 95%"],
      ["Protection", "Over/under-voltage, overload, over-temp, short-circuit"],
      ["Restart delay", "Short 5s / Long 200s"],
    ],
    packing: { productSize: "43.8 × 34.4 × 18.5 cm", packSize: "49 × 39.5 × 23 cm", nw: "25.3 kg", gw: "26.3 kg" },
  },
  {
    id: "vt-svc-1k",
    name: "SVC Servo Stabilizer — 1kVA",
    category: "Voltage Stabilizers",
    categoryId: "stabilizers",
    tech: "SVC",
    tagline: "Protects one TV, router and lights — or a single fridge.",
    highlight: ["1kVA", "single point"],
    description:
      "The smallest servo stabilizer — for one TV, a router and lights, or a single refrigerator. A real servo motor and autotransformer hold a steady 220V across a wide 150V–270V input, so your electronics ride out the sags and surges. Quiet, copper-wound, and backed by our own service team.",
    image: "assets/svc-stabilizer.png",
    specs: [
      ["Technology", "SVC — servo motor"],
      ["Capacity", "1kVA, single-phase"],
      ["Input range", "150V – 270V AC (lower on request)"],
      ["Output", "220V ±1%"],
      ["Efficiency", "> 96%"],
      ["Display", "LED, voltage + load"],
      ["Protection", "High/low-voltage cutoff, overload, time delay"],
    ],
  },
  {
    id: "vt-svc-3k",
    name: "SVC Servo Stabilizer — 3kVA",
    category: "Voltage Stabilizers",
    categoryId: "stabilizers",
    tech: "SVC",
    tagline: "Right for a single AC or a room of sensitive electronics.",
    highlight: ["3kVA", "one AC"],
    description:
      "A 3kVA servo stabilizer for one air-conditioner or a room of sensitive electronics. The servo motor sweeps a slider across a real autotransformer for smooth, stepless correction — not the stepped jumps of cheap relay units. Holds 220V across a wide 150V–270V input, with copper windings and a time-delay restart that protects compressors.",
    image: "assets/svc-stabilizer.png",
    specs: [
      ["Technology", "SVC — servo motor"],
      ["Capacity", "3kVA, single-phase"],
      ["Input range", "150V – 270V AC (lower on request)"],
      ["Output", "220V ±1%"],
      ["Efficiency", "> 96%"],
      ["Display", "LED, voltage + load"],
      ["Protection", "High/low-voltage cutoff, overload, time delay"],
    ],
  },
  {
    id: "vt-svc-5k",
    name: "SVC Servo Stabilizer — 5kVA",
    category: "Voltage Stabilizers",
    categoryId: "stabilizers",
    tech: "SVC",
    badge: "Best seller",
    tagline: "A popular home servo stabilizer in Punjab.",
    highlight: ["140–260V", "input range"],
    description:
      "The right size for one inverter AC, a fridge, lights, and a TV. This servo motor stabilizer has a real autotransformer, a wide 150V–270V input range, and a powder-coated steel cabinet. The dual LED display shows live voltage and load. It is quiet enough for a bedroom utility cupboard, and it is backed by our own service team.",
    image: "assets/svc-stabilizer.png",
    specs: [
      ["Technology", "SVC — servo motor"],
      ["Capacity", "5kVA, single-phase"],
      ["Input range", "150V – 270V AC (lower on request)"],
      ["Output", "220V ±1%"],
      ["Correction speed", "25V / second"],
      ["Efficiency", "> 96%"],
      ["Display", "Dual LED, voltage + load"],
      ["Dimensions", "340 × 240 × 260 mm"],
    ],
  },
  {
    id: "vt-svc-7k",
    name: "SVC Servo Stabilizer — 7kVA",
    category: "Voltage Stabilizers",
    categoryId: "stabilizers",
    tech: "SVC",
    tagline: "Holds one to two ACs plus the home's electronics.",
    highlight: ["7kVA", "1–2 ACs"],
    description:
      "A 7kVA servo stabilizer for one to two air-conditioners plus the fridge, fans and electronics. Smooth servo correction keeps a steady 220V even when evening voltage drops, across a wide 150V–270V input. Copper windings, large contacts, and an LCD that shows live voltage and load.",
    image: "assets/svc-stabilizer.png",
    specs: [
      ["Technology", "SVC — servo motor"],
      ["Capacity", "7kVA, single-phase"],
      ["Input range", "150V – 270V AC (lower on request)"],
      ["Output", "220V ±1%"],
      ["Efficiency", "> 96%"],
      ["Display", "LCD, voltage + load"],
      ["Protection", "High/low-voltage cutoff, overload, time delay"],
    ],
  },
  {
    id: "vt-svc-10k",
    name: "SVC Servo Stabilizer — 10kVA",
    category: "Voltage Stabilizers",
    categoryId: "stabilizers",
    tech: "SVC",
    tagline: "Keeps two ACs and the rest of the house steady.",
    highlight: ["±1%", "output accuracy"],
    description:
      "Step up to whole-home coverage. This 10kVA servo stabilizer moves a carbon-brush slider across a variable autotransformer for smooth correction, not the stepped jumps of cheap relay units. It handles two inverter ACs plus the fridge, fans, and electronics. It has copper windings, large contacts, and an LCD that shows live input, output, and load.",
    image: "assets/svc-stabilizer.png",
    specs: [
      ["Technology", "SVC — servo motor"],
      ["Capacity", "10kVA, single-phase"],
      ["Input range", "150V – 270V AC (lower on request)"],
      ["Output", "220V ±1%"],
      ["Correction speed", "28V / second"],
      ["Efficiency", "> 96%"],
      ["Display", "LCD, voltage + load + runtime"],
      ["Dimensions", "440 × 320 × 360 mm"],
    ],
  },
  {
    id: "vt-svc-15k",
    name: "SVC Servo Stabilizer — 15kVA",
    category: "Voltage Stabilizers",
    categoryId: "stabilizers",
    tech: "SVC",
    tagline: "Covers the whole home — geyser, ACs, motors, electronics.",
    highlight: ["15kVA", "whole-home"],
    description:
      "Smooth, steady voltage the moment your mains acts up. This servo motor (SVC type) stabilizer moves a carbon-brush slider across an autotransformer, not a stepped relay. So your AC, motors, and electronics get steady 220V even when WAPDA gives you 150V or 270V. It has copper windings, large contacts, and a thermal-cutoff controller. This design has run in Pakistani homes and shops for over 15 years.",
    image: "assets/svc-stabilizer.png",
    specs: [
      ["Technology", "SVC — servo motor"],
      ["Capacity", "15kVA, single-phase"],
      ["Input range", "150V – 270V AC (lower on request)"],
      ["Output", "220V ±1%"],
      ["Correction speed", "30V / second"],
      ["Efficiency", "> 96%"],
      ["Display", "LCD with voltage, load, runtime"],
      ["Dimensions", "520 × 380 × 420 mm"],
    ],
  },
  {
    id: "vt-svc-20k",
    name: "SVC Servo Stabilizer — 20kVA",
    category: "Voltage Stabilizers",
    categoryId: "stabilizers",
    tech: "SVC",
    tagline: "For a large home or shop — available single or 3-phase.",
    highlight: ["20kVA", "home or shop"],
    description:
      "A 20kVA servo stabilizer for a large home, shop or light commercial load. Stepless servo correction holds a steady 220V across a wide 150V–270V input, with heavy copper windings and large contacts built for continuous load. Available single-phase or three-phase, made to your supply.",
    image: "assets/svc-stabilizer.png",
    specs: [
      ["Technology", "SVC — servo motor"],
      ["Capacity", "20kVA, single or 3-phase"],
      ["Input range", "150V – 270V AC (lower on request)"],
      ["Output", "220V ±1%"],
      ["Efficiency", "> 96%"],
      ["Display", "LCD, voltage + load"],
      ["Protection", "High/low-voltage cutoff, overload, time delay"],
    ],
  },
  {
    id: "vt-svc-30k",
    name: "SVC Servo Stabilizer — 30kVA",
    category: "Voltage Stabilizers",
    categoryId: "stabilizers",
    tech: "SVC",
    tagline: "Large shop or commercial load — single or 3-phase.",
    highlight: ["30kVA", "commercial"],
    description:
      "The largest single-unit servo in the range — 30kVA for a large shop, small factory or commercial load. Smooth servo correction holds 220V across a wide 150V–270V input, with heavy-duty copper windings and contacts rated for continuous duty. Available single-phase or three-phase, built to order.",
    image: "assets/svc-stabilizer.png",
    specs: [
      ["Technology", "SVC — servo motor"],
      ["Capacity", "30kVA, single or 3-phase"],
      ["Input range", "150V – 270V AC (lower on request)"],
      ["Output", "220V ±1%"],
      ["Efficiency", "> 96%"],
      ["Display", "LCD, voltage + load"],
      ["Protection", "High/low-voltage cutoff, overload, time delay"],
    ],
  },
  {
    id: "vt-avr-a25",
    name: "Voltec A-25 — Refrigerator Stabilizer (2500W)",
    category: "Voltage Stabilizers",
    categoryId: "stabilizers",
    tech: "AVR",
    tagline: "Automatic stabilizer for fridges and deep freezers — 2500W, pure copper.",
    useFor: "6–18 cu ft fridge or deep freezer",
    highlight: ["A-25", "2500W"],
    description:
      "Voltec's A-25 is an automatic voltage stabilizer for refrigerators and deep freezers (6–18 cubic feet). 2500W, 100% pure copper, with fast, accurate relay correction and a time-delay system that protects the compressor. Works from very low voltage and holds a steady 220V. Available in 150V, 120V, 100V and 70V input versions with 3, 4, 5 or 7 relays.",
    image: "assets/avr-a25.png",
    specs: [
      ["Model", "Voltec A-25"],
      ["Capacity", "2500W"],
      ["Best for", "Fridge / deep freezer (6–18 cu ft)"],
      ["Output", "220V"],
      ["Input options", "150V / 120V / 100V / 70V"],
      ["Relays", "3 / 4 / 5 / 7"],
      ["Contact material", "100% pure copper"],
      ["Protection", "Time-delay, high/low-voltage cutoff"],
    ],
  },
  {
    id: "vt-avr-a50",
    name: "Voltec A-50 — Split AC Stabilizer (5000W)",
    category: "Voltage Stabilizers",
    categoryId: "stabilizers",
    tech: "AVR",
    tagline: "Energy-saver stabilizer for 1–1.5 ton split ACs — 5000W.",
    useFor: "1 / 1.5 ton split AC",
    highlight: ["A-50", "5000W"],
    description:
      "Voltec's A-50 (Energy Saver) is a 5000W automatic voltage stabilizer for 1 to 1.5 ton split air-conditioners. 100% pure copper, with a wide 100–260V input held to a steady 220V output, relay correction and overload protection. Available in 150V input with 2 relays.",
    image: "assets/avr-a50.png",
    specs: [
      ["Model", "Voltec A-50 (Energy Saver)"],
      ["Capacity", "5000W"],
      ["Best for", "1 / 1.5 ton split AC"],
      ["Input range", "100V – 260V AC"],
      ["Output", "220V"],
      ["Relays", "2"],
      ["Contact material", "100% pure copper"],
    ],
  },
  {
    id: "vt-avr-a100-r2",
    name: "Voltec A-100 R2 — AC Stabilizer",
    category: "Voltage Stabilizers",
    categoryId: "stabilizers",
    tech: "AVR",
    tagline: "10,000W AC stabilizer — works from 150V.",
    useFor: "1 / 1.5 ton AC (inverter)",
    highlight: ["R2", "from 150V"],
    description:
      "Voltec A-100 R2 — a 10,000W automatic voltage stabilizer for a 1 to 1.5 ton air-conditioner. Holds a steady 220V across a 150V–270V input, with 99.99% pure copper and relay correction that protects the compressor. For areas with lighter voltage sag.",
    image: "assets/r2_voltec.webp",
    specs: [
      ["Model", "Voltec A-100 R2"],
      ["Capacity", "10000W"],
      ["Best for", "1 / 1.5 ton AC (inverter)"],
      ["Input range", "150V – 270V AC"],
      ["Output", "220V"],
      ["Contact material", "99.99% pure copper"],
    ],
  },
  {
    id: "vt-avr-a100-r3",
    name: "Voltec A-100 R3 — AC Stabilizer",
    category: "Voltage Stabilizers",
    categoryId: "stabilizers",
    tech: "AVR",
    tagline: "10,000W AC stabilizer — works from 120V. Most popular.",
    useFor: "1 / 1.5 ton AC (inverter & normal)",
    highlight: ["R3", "from 120V"],
    description:
      "Voltec A-100 R3 — the most popular AC stabilizer. 10,000W, holds a steady 220V across a wide 120V–270V input for inverter and normal 1 to 1.5 ton ACs. 99.99% pure copper, relay correction and compressor protection.",
    image: "assets/r3_voltec.webp",
    specs: [
      ["Model", "Voltec A-100 R3"],
      ["Capacity", "10000W"],
      ["Best for", "1 / 1.5 ton AC (inverter & normal)"],
      ["Input range", "120V – 270V AC"],
      ["Output", "220V"],
      ["Contact material", "99.99% pure copper"],
    ],
  },
  {
    id: "vt-avr-a100-r4",
    name: "Voltec A-100 R4 — AC Stabilizer",
    category: "Voltage Stabilizers",
    categoryId: "stabilizers",
    tech: "AVR",
    tagline: "10,000W AC stabilizer — works from just 100V.",
    useFor: "1 / 1.5 ton AC (inverter & normal)",
    highlight: ["R4", "from 100V"],
    description:
      "Voltec A-100 R4 — built for severe low-voltage areas. A 10,000W AC stabilizer that works from as low as 100V and holds a steady 220V (100V–270V input) for inverter and normal 1 to 1.5 ton ACs. 99.99% pure copper with compressor protection.",
    image: "assets/r4_voltec.webp",
    specs: [
      ["Model", "Voltec A-100 R4"],
      ["Capacity", "10000W"],
      ["Best for", "1 / 1.5 ton AC (inverter & normal)"],
      ["Input range", "100V – 270V AC"],
      ["Output", "220V"],
      ["Contact material", "99.99% pure copper"],
    ],
  },

  // ===== INDUSTRIAL STABILIZERS =====
  {
    id: "vt-ind-100k",
    name: "3-Phase Industrial Stabilizer — 100kVA",
    category: "3-Phase Industrial Stabilizers",
    categoryId: "industrial",
    tech: "SVC",
    badge: "3-Phase",
    tagline: "3-phase servo stabilizer for factories, mills, and commercial buildings.",
    highlight: ["100kVA", "3-phase"],
    description:
      "Built for plants that cannot lose a single shift. This 100kVA three-phase servo stabilizer fixes each phase on its own. So unbalanced WAPDA supply becomes clean, balanced 400V at the output. It has heavy copper windings, large contactors, forced-air cooling, and a thermal-protected controller rated for 50°C non-stop. It runs in textile and food plants across Punjab.",
    image: "assets/industrial-sjw.png",
    specs: [
      ["Technology", "SVC — 3-phase servo"],
      ["Capacity", "100kVA, 3-phase"],
      ["Input range", "300V – 460V (L-L)"],
      ["Output", "400V ±1%"],
      ["Correction speed", "35V / second"],
      ["Efficiency", "> 97%"],
      ["Ambient rating", "50°C continuous"],
      ["Cooling", "Forced air, thermal cutoff"],
    ],
  },
  {
    id: "vt-ind-200k",
    name: "3-Phase Industrial Stabilizer — 200kVA",
    category: "3-Phase Industrial Stabilizers",
    categoryId: "industrial",
    tech: "SVC",
    badge: "Heavy duty",
    tagline: "Heavy industrial servo stabilizer — the one running K&N's lines.",
    highlight: ["200kVA", "50°C rated"],
    description:
      "Built for factories that cannot lose a single shift. Three separate servo motors move variable autotransformers, one per phase, to fix voltage at 35V per second. It has heavy copper windings, large contactors, and a thermal-protected control board that runs 24/7 in 50°C heat. It runs at K&N's, Fauji Fertilizer, and dozens of textile mills across Punjab.",
    image: "assets/industrial-sjw.png",
    specs: [
      ["Technology", "SVC — 3-phase servo"],
      ["Capacity", "200kVA, 3-phase"],
      ["Input range", "280V – 480V (L-L)"],
      ["Output", "400V ±1%"],
      ["Correction speed", "35V / second"],
      ["Efficiency", "> 97%"],
      ["Ambient rating", "50°C continuous"],
      ["Cooling", "Forced air, thermal cutoff"],
    ],
  },
  {
    id: "vt-ind-500k",
    name: "3-Phase Industrial Stabilizer — 500kVA",
    category: "3-Phase Industrial Stabilizers",
    categoryId: "industrial",
    tech: "SVC",
    tagline: "Half-megawatt servo stabilizer that fixes very low voltage.",
    highlight: ["500kVA", "oil-cooled"],
    description:
      "When your factory pulls half a megawatt and the input voltage swings 200V on a hot afternoon, this keeps you running. It is a forced-oil-cooled three-phase servo stabilizer that fixes very low voltage down to 260V L-L. It has heavy copper, thermostatic monitoring, and a control system that has run non-stop in textile mills, cold stores, and dairy plants across Pakistan for over 15 years. Custom builds on request.",
    image: "assets/industrial-sjw.png",
    specs: [
      ["Technology", "SVC — 3-phase servo"],
      ["Capacity", "500kVA, 3-phase"],
      ["Input range", "260V – 480V (L-L)"],
      ["Output", "400V ±1%"],
      ["Correction speed", "45V / second"],
      ["Efficiency", "> 97.5%"],
      ["Cooling", "Forced oil, thermostatic"],
      ["Ambient rating", "50°C continuous"],
    ],
  },

  // ===== LITHIUM CELLS =====
  {
    id: "vt-eve-lf100",
    name: "EVE LF100LA — 3.2V 100Ah LFP Cell",
    category: "Lithium Cells",
    categoryId: "cells",
    tech: "LFP",
    badge: "Most shipped",
    price: 11500,
    tagline: "Genuine EVE Grade-A LF100LA 100Ah prismatic cell — our most-shipped product.",
    highlight: ["5,000+", "cycles"],
    cell: {
      format: "Prismatic LFP",
      capacityAh: "100",
      voltageV: "3.2",
      cycles: "5,000+",
      weight: "2.0 kg",
      size: "174 × 72 × 207 mm",
      cRate: "0.5C / 0.5C",
      applications: ["Home solar storage", "Telecom & base stations", "UPS & backup", "Commercial ESS"],
      features: ["Lithium iron phosphate (LiFePO4)", "5,000+ cycle life", "High safety (LFP)", "Low internal resistance", "Grade-A matched in Lahore", "QR-traceable, full test report"],
      certifications: ["ISO 9001", "CE", "UN38.3", "RoHS", "REACH", "UL", "IEC"],
      gallery: ["/assets/cells/cell-1.webp", "/assets/cells/cell-2.webp", "/assets/cells/cell-3.webp", "/assets/cells/cell-4.webp"],
      videos: [
        { src: "/assets/cells/cell-video-1.mp4", poster: "/assets/cells/cell-video-1-poster.webp" },
        { src: "/assets/cells/cell-video-2.mp4", poster: "/assets/cells/cell-video-2-poster.webp" },
      ],
      cartonSize: 8,
    },
    description:
      "Genuine EVE 3.2V 100Ah Grade-A lithium iron phosphate (LiFePO4) prismatic cell — direct from EVE Energy. Used to build lithium batteries.",
    image: "assets/cells/cell-hero.webp",
    specs: [
      ["Chemistry", "Lithium iron phosphate (LiFePO4)"],
      ["Nominal voltage", "3.2V"],
      ["Capacity", "100Ah (320Wh) at 0.5C, 25°C"],
      ["Cycle life", "5,000+ at 80% DoD"],
      ["Operating temp", "-20°C to +55°C"],
      ["Internal resistance", "< 0.5 mΩ"],
      ["Dimensions", "174 × 72 × 207 mm"],
      ["Weight", "2.0 kg"],
      ["Origin", "EVE Energy, China"],
      ["Grade", "Grade-A, QR-traceable"],
      ["Minimum order", "1 carton (8 cells)"],
    ],
  },

  // ===== ELECTRIC PARTS (BMS, relays, LED displays) =====
  {
    id: "vt-bms-16s",
    name: "DALY BMS — 16S 100A Active Balancing",
    category: "Electric Parts",
    categoryId: "parts",
    tech: "BMS",
    hidden: true,
    tagline: "16-series LFP protection with active balancing and CAN for inverters.",
    highlight: ["16S", "CAN-ready"],
    description:
      "The control board that turns 16 cells into a real battery. This DALY active-balancing BMS keeps every cell within 5mV of the others, even after years of use. CAN protocols let it talk to Victron, Deye, SRNE, and Growatt inverters right out of the box. It ships with our tested firmware and a 72-hour bench test report — not generic AliExpress firmware.",
    image: "assets/bms-daly.png",
    specs: [
      ["Configuration", "16S (48V nominal LFP)"],
      ["Continuous current", "100A"],
      ["Peak current", "200A for 10s"],
      ["Balancing", "Active, 2A capacitor bridge"],
      ["Communication", "UART, RS485, CAN 2.0B"],
      ["Inverter protocols", "Victron, Deye, SRNE, Growatt"],
      ["Dimensions", "195 × 120 × 32 mm"],
    ],
  },
  {
    id: "vt-relay-t73",
    name: "Wirell T73 PCB Relay — 5A/7A/10A",
    category: "Electric Parts",
    categoryId: "parts",
    tech: "Relay",
    tagline: "Compact PCB power relay (JQC-3F) for control boards — up to 10A.",
    highlight: ["T73", "up to 10A"],
    description:
      "The small power relay every control board needs — Wirell's JQC-3F (T73). Silver-alloy contacts switch up to 10A, with a 99% pure-copper coil for a long, reliable life. Built for stabilizer controllers, inverters, solar charge controllers and automation panels. Standard PCB through-hole footprint. Stocked by the thousand for next-day dispatch.",
    image: "assets/relay-t73.webp",
    specs: [
      ["Model", "Wirell JQC-3F (T73)"],
      ["Contact rating", "7A @ 250VAC · 10A @ 125VAC · 5A @ 30VDC"],
      ["Max switching power", "1750VA / 120W"],
      ["Contact material", "Silver alloy"],
      ["Coil", "Pure copper (99%)"],
      ["Operate / release time", "≤ 10ms / ≤ 5ms"],
      ["Electrical life", "100,000+ cycles"],
      ["Mechanical life", "2,000,000+ cycles"],
      ["Insulation", "500MΩ · 750VAC / 1 min"],
      ["Mounting", "PCB through-hole"],
      ["Operating temp", "-25°C to +55°C"],
    ],
  },
  {
    id: "vt-relay-t90",
    name: "Wirell T90 PCB Relay — 20A/30A/40A",
    category: "Electric Parts",
    categoryId: "parts",
    tech: "Relay",
    tagline: "Heavy-duty PCB power relay (JQX-15F) for high-current switching — up to 40A.",
    highlight: ["T90", "up to 40A"],
    description:
      "Wirell's JQX-15F (T90) is the heavy-duty PCB relay for high-current switching — up to 40A. Available in 1A, 1B and 1C contact forms with silver-alloy contacts that take real motor and inrush loads. The switching heart of AVR stabilizers, inverters and power panels. Standard PCB through-hole footprint. Stocked by the thousand for next-day dispatch.",
    image: "assets/relay-t90.png",
    specs: [
      ["Model", "Wirell JQX-15F (T90)"],
      ["Contact rating", "20A / 30A / 40A"],
      ["Max switching capacity", "30A @ 250VAC / 30VDC"],
      ["Switching power", "AC 7500VA / 900W · DC 5000VA / 600W"],
      ["Contact form", "1A / 1B / 1C"],
      ["Contact material", "Silver alloy"],
      ["Coil power", "0.9W (DC) · 12VA (AC)"],
      ["Operate / release time", "< 15ms / < 10ms"],
      ["Electrical life", "100,000+ cycles"],
      ["Mechanical life", "2,000,000+ cycles"],
      ["Insulation", "500MΩ · 1500VAC / 1 min"],
      ["Mounting", "PCB through-hole"],
      ["Operating temp", "-40°C to +70°C"],
    ],
  },
  {
    id: "vt-led-5630",
    name: "7-Segment LED Display — 5630",
    category: "Electric Parts",
    categoryId: "parts",
    tech: "LED",
    tagline: "Bright 7-segment display module for stabilizer and meter panels.",
    highlight: ["5630", "7-segment"],
    description:
      "A 5630-series 7-segment LED display module for stabilizer fronts, panel meters, and instruments. Bright segments with a wide viewing angle. Supplied to makers and repair workshops across Pakistan.",
    image: "assets/prod-relay.jpg",
    specs: [
      ["Type", "7-segment LED display"],
      ["Series", "5630"],
      ["Colour", "Red (others on request)"],
      ["Application", "Stabilizer / meter panels"],
      ["Warranty", "Manufacturer defect"],
    ],
  },
  {
    id: "vt-led-4630",
    name: "7-Segment LED Display — 4630",
    category: "Electric Parts",
    categoryId: "parts",
    tech: "LED",
    tagline: "Small 7-segment display module for instrument and control panels.",
    highlight: ["4630", "7-segment"],
    description:
      "A 4630-series 7-segment LED display module for small instrument readouts and control panels. Bright, even segments give clear voltage and load readouts. Stocked at our Lahore warehouse.",
    image: "assets/prod-relay.jpg",
    specs: [
      ["Type", "7-segment LED display"],
      ["Series", "4630"],
      ["Colour", "Red (others on request)"],
      ["Application", "Instrument / control panels"],
      ["Warranty", "Manufacturer defect"],
    ],
  },
];

export const CATEGORIES: Category[] = [
  { id: "all", label: "All products", count: 26 },
  { id: "stabilizers", label: "Stabilizers", count: 13 },
  { id: "cells", label: "Lithium Cells", count: 1 },
  { id: "industrial", label: "3-Phase Industrial", count: 4 },
  { id: "parts", label: "Electric Parts", count: 4 },
];

export function getProduct(id: string): Product | undefined {
  return PRODUCTS.find((p) => p.id === id);
}

export function relatedProducts(p: Product, limit = 3): Product[] {
  return PRODUCTS.filter(
    (x) => x.id !== p.id && x.categoryId === p.categoryId,
  ).slice(0, limit);
}
