import type { Product, Category } from "./types";

export const VOLTEC_WHATSAPP = "923244004778";

export function whatsappLink(productName?: string): string {
  const text = productName
    ? `Hi Voltec! I'm interested in ordering: ${productName}. Please share details.`
    : "Hi Voltec! I'd like to place an order.";
  return `https://wa.me/${VOLTEC_WHATSAPP}?text=${encodeURIComponent(text)}`;
}

// Voltec sells electrical PRODUCTS across Pakistan — voltage stabilizers (IGBT,
// SVC, AVR), industrial stabilizers, lithium cells, and supporting electronics.
export const PRODUCTS: Product[] = [
  // ===== INVERTER (IGBT) STABILIZERS — ADA series, 6 models =====
  // Specs from the factory data sheet (ADA-A series). Same engineering across
  // the range; capacity, current, no-load loss, size and weight vary per model.
  {
    id: "vt-igbt-550",
    name: "IGBT Inverter Stabilizer — 550VA",
    category: "Voltage Stabilizers",
    categoryId: "stabilizers",
    tech: "IGBT",
    showcase: "stabilizer",
    status: "upcoming",
    tagline: "A small inverter stabilizer for a TV, router and lights.",
    useFor: "Sensitive electronics & instruments",
    highlight: ["550VA", "plug & play"],
    description:
      "A small inverter stabilizer for a TV, router and a few lights. It fixes voltage instantly (0 ms) with no moving parts. The wide 90–310V input holds a steady 220V even when the voltage drops. Pure sine output, ≥96% efficient.",
    image: "assets/prod-igbt.jpg",
    specs: [
      ["Technology", "IGBT inverter (no moving parts)"],
      ["Capacity", "550VA, single-phase"],
      ["Rated current", "2.5A"],
      ["Input range", "90V – 310V AC"],
      ["Output", "220V / 230V"],
      ["Output accuracy", "±2%"],
      ["Response time", "0 ms"],
      ["Waveform", "Pure sine (THD < 3%)"],
      ["Efficiency", "≥ 96%"],
      ["No-load loss", "10W"],
    ],
    packing: { productSize: "23 × 17 × 8.85 cm", packSize: "49 × 29.5 × 24.5 cm", nw: "2.1 kg", gw: "2.4 kg" },
  },
  {
    id: "vt-igbt-2k",
    name: "IGBT Inverter Stabilizer — 2kVA",
    category: "Voltage Stabilizers",
    categoryId: "stabilizers",
    tech: "IGBT",
    showcase: "stabilizer",
    status: "upcoming",
    tagline: "For one AC or a room full of electronics.",
    useFor: "Lab, medical & office equipment",
    highlight: ["2kVA", "0 ms"],
    description:
      "For a single AC or a room of electronics. It corrects voltage instantly (0 ms) with no servo motor and no brushes. The wide 90–310V input holds 220V through sags and surges. Pure sine, ≥96% efficient and silent.",
    image: "assets/prod-igbt.jpg",
    specs: [
      ["Technology", "IGBT inverter (no moving parts)"],
      ["Capacity", "2kVA, single-phase"],
      ["Rated current", "10A"],
      ["Input range", "90V – 310V AC"],
      ["Output", "220V / 230V"],
      ["Output accuracy", "±2%"],
      ["Response time", "0 ms"],
      ["Waveform", "Pure sine (THD < 3%)"],
      ["Efficiency", "≥ 96%"],
      ["No-load loss", "19W"],
    ],
    packing: { productSize: "27.8 × 20.5 × 10.17 cm", packSize: "56 × 34.5 × 27 cm", nw: "3.3 kg", gw: "3.6 kg" },
  },
  {
    id: "vt-igbt-5k",
    name: "IGBT Inverter Stabilizer — 5kVA",
    category: "Voltage Stabilizers",
    categoryId: "stabilizers",
    tech: "IGBT",
    showcase: "stabilizer",
    status: "upcoming",
    tagline: "For a small home — one or two ACs plus the basics.",
    useFor: "Clinics, small laser & CNC",
    highlight: ["5kVA", "pure sine"],
    description:
      "For a small home — one or two ACs plus fridge, fans and electronics. Instant inverter correction, no moving parts, ≥96% efficient. Pure sine output keeps sensitive appliances safe.",
    image: "assets/prod-igbt.jpg",
    specs: [
      ["Technology", "IGBT inverter (no moving parts)"],
      ["Capacity", "5kVA, single-phase"],
      ["Rated current", "25A"],
      ["Input range", "90V – 310V AC"],
      ["Output", "220V / 230V"],
      ["Output accuracy", "±2%"],
      ["Response time", "0 ms"],
      ["Waveform", "Pure sine (THD < 3%)"],
      ["Efficiency", "≥ 96%"],
      ["No-load loss", "31W"],
    ],
    packing: { productSize: "37 × 29 × 12.2 cm", packSize: "43 × 34 × 16 cm", nw: "7.3 kg", gw: "8 kg" },
  },
  {
    id: "vt-igbt-10k",
    name: "IGBT Inverter Stabilizer — 10kVA",
    category: "Voltage Stabilizers",
    categoryId: "stabilizers",
    tech: "IGBT",
    badge: "Flagship",
    showcase: "stabilizer",
    status: "upcoming",
    tagline: "Covers a full home on clean, steady power.",
    useFor: "Laser & CNC machines",
    highlight: ["10kVA", "whole home"],
    description:
      "Covers a full home — many ACs, motors and electronics — on clean, steady 220V. Instant 0 ms inverter correction with no servo motor to service. Wide 90–310V input, pure sine output, ≥96% efficient.",
    image: "assets/prod-igbt.jpg",
    specs: [
      ["Technology", "IGBT inverter (no moving parts)"],
      ["Capacity", "10kVA, single-phase"],
      ["Rated current", "50A"],
      ["Input range", "90V – 310V AC"],
      ["Output", "220V / 230V"],
      ["Output accuracy", "±2%"],
      ["Response time", "0 ms"],
      ["Waveform", "Pure sine (THD < 3%)"],
      ["Efficiency", "≥ 96%"],
      ["No-load loss", "65W"],
    ],
    packing: { productSize: "50 × 39 × 14.2 cm", packSize: "56 × 44 × 18.5 cm", nw: "12.7 kg", gw: "13.7 kg" },
  },
  {
    id: "vt-igbt-15k",
    name: "IGBT Inverter Stabilizer — 15kVA",
    category: "Voltage Stabilizers",
    categoryId: "stabilizers",
    tech: "IGBT",
    showcase: "stabilizer",
    status: "upcoming",
    tagline: "Whole-home and small-shop power.",
    useFor: "Large laser & production lines",
    highlight: ["15kVA", "0 ms"],
    description:
      "Whole-home and small-shop power — geysers, ACs, motors and electronics. Instant inverter correction, no moving parts, ≥96% efficient. Holds 220V through deep voltage drops.",
    image: "assets/prod-igbt.jpg",
    specs: [
      ["Technology", "IGBT inverter (no moving parts)"],
      ["Capacity", "15kVA, single-phase"],
      ["Rated current", "75A"],
      ["Input range", "90V – 310V AC"],
      ["Output", "220V / 230V"],
      ["Output accuracy", "±2%"],
      ["Response time", "0 ms"],
      ["Waveform", "Pure sine (THD < 3%)"],
      ["Efficiency", "≥ 96%"],
      ["No-load loss", "75W"],
    ],
    packing: { productSize: "50 × 41 × 21.2 cm", packSize: "56 × 46 × 25.5 cm", nw: "19.5 kg", gw: "22 kg" },
  },
  {
    id: "vt-igbt-20k",
    name: "IGBT Inverter Stabilizer — 20kVA",
    category: "Voltage Stabilizers",
    categoryId: "stabilizers",
    tech: "IGBT",
    showcase: "stabilizer",
    status: "upcoming",
    tagline: "Large home or shop load on clean, steady power.",
    useFor: "Heavy precision machinery",
    highlight: ["20kVA", "≥96%"],
    description:
      "A large home or shop load on clean, steady power. Instant 0 ms inverter correction, sealed and silent, ≥96% efficient. The wide 90–310V input rides through the worst sags and surges.",
    image: "assets/prod-igbt.jpg",
    specs: [
      ["Technology", "IGBT inverter (no moving parts)"],
      ["Capacity", "20kVA, single-phase"],
      ["Rated current", "100A"],
      ["Input range", "90V – 310V AC"],
      ["Output", "220V / 230V"],
      ["Output accuracy", "±2%"],
      ["Response time", "0 ms"],
      ["Waveform", "Pure sine (THD < 3%)"],
      ["Efficiency", "≥ 96%"],
      ["No-load loss", "85W"],
    ],
    packing: { productSize: "50 × 41 × 21.2 cm", packSize: "56 × 46 × 25.5 cm", nw: "22 kg", gw: "23.2 kg" },
  },
  {
    id: "vt-svc-5k",
    name: "SVC Servo Stabilizer — 5kVA",
    category: "Voltage Stabilizers",
    categoryId: "stabilizers",
    tech: "SVC",
    badge: "Best seller",
    tagline: "A popular home servo stabilizer in Punjab.",
    highlight: ["140–260V", "input range"],
    description:
      "The right size for one inverter AC, a fridge, lights, and a TV. This servo motor stabilizer has a real autotransformer, a wide 140V–260V input range, and a powder-coated steel cabinet. The dual LED display shows live voltage and load. It is quiet enough for a bedroom utility cupboard, and it is backed by our own service team.",
    image: "assets/prod-residential.png",
    specs: [
      ["Technology", "SVC — servo motor"],
      ["Capacity", "5kVA, single-phase"],
      ["Input range", "140V – 260V AC"],
      ["Output", "220V ±1%"],
      ["Correction speed", "25V / second"],
      ["Efficiency", "> 96%"],
      ["Display", "Dual LED, voltage + load"],
      ["Dimensions", "340 × 240 × 260 mm"],
    ],
  },
  {
    id: "vt-svc-10k",
    name: "SVC Servo Stabilizer — 10kVA",
    category: "Voltage Stabilizers",
    categoryId: "stabilizers",
    tech: "SVC",
    tagline: "Keeps two ACs and the rest of the house steady.",
    highlight: ["±1%", "output accuracy"],
    description:
      "Step up to whole-home coverage. This 10kVA servo stabilizer moves a carbon-brush slider across a variable autotransformer for smooth correction, not the stepped jumps of cheap relay units. It handles two inverter ACs plus the fridge, fans, and electronics. It has copper windings, large contacts, and an LCD that shows live input, output, and load.",
    image: "assets/prod-residential.png",
    specs: [
      ["Technology", "SVC — servo motor"],
      ["Capacity", "10kVA, single-phase"],
      ["Input range", "140V – 270V AC"],
      ["Output", "220V ±1%"],
      ["Correction speed", "28V / second"],
      ["Efficiency", "> 96%"],
      ["Display", "LCD, voltage + load + runtime"],
      ["Dimensions", "440 × 320 × 360 mm"],
    ],
  },
  {
    id: "vt-svc-15k",
    name: "SVC Servo Stabilizer — 15kVA",
    category: "Voltage Stabilizers",
    categoryId: "stabilizers",
    tech: "SVC",
    tagline: "Covers the whole home — geyser, ACs, motors, electronics.",
    highlight: ["15kVA", "whole-home"],
    description:
      "Smooth, steady voltage the moment your mains acts up. This servo motor (SVC type) stabilizer moves a carbon-brush slider across an autotransformer, not a stepped relay. So your AC, motors, and electronics get steady 220V even when WAPDA gives you 140V or 260V. It has copper windings, large contacts, and a thermal-cutoff controller. This design has run in Pakistani homes and shops for over 15 years.",
    image: "assets/prod-residential.png",
    specs: [
      ["Technology", "SVC — servo motor"],
      ["Capacity", "15kVA, single-phase"],
      ["Input range", "140V – 280V AC"],
      ["Output", "220V ±1%"],
      ["Correction speed", "30V / second"],
      ["Efficiency", "> 96%"],
      ["Display", "LCD with voltage, load, runtime"],
      ["Dimensions", "520 × 380 × 420 mm"],
    ],
  },
  {
    id: "vt-avr-1k",
    name: "AVR Voltage Stabilizer — 1kVA",
    category: "Voltage Stabilizers",
    categoryId: "stabilizers",
    tech: "AVR",
    badge: "Entry",
    tagline: "Low-cost relay AVR for a TV, router, and lights.",
    highlight: ["1kVA", "plug & play"],
    description:
      "Simple protection for one sensitive appliance. This AVR (automatic voltage regulator) uses fast relay tap-switching to keep your TV, router, computer, or sound system safe from spikes and sags. It is small, fits on a wall, and just plugs in — no installation needed. A reliable first step into proper voltage protection at a price every home can manage.",
    image: "assets/prod-avr.jpg",
    specs: [
      ["Technology", "AVR — relay tap-switching"],
      ["Capacity", "1kVA, single-phase"],
      ["Input range", "150V – 260V AC"],
      ["Output", "220V ±5%"],
      ["Response time", "< 1 second"],
      ["Protection", "Over/under-voltage cutoff, delay"],
      ["Mounting", "Wall or desktop"],
    ],
  },
  {
    id: "vt-avr-3k",
    name: "AVR Voltage Stabilizer — 3kVA",
    category: "Voltage Stabilizers",
    categoryId: "stabilizers",
    tech: "AVR",
    tagline: "Relay AVR for one AC or a room full of electronics.",
    highlight: ["3kVA", "fast relay"],
    description:
      "A tough AVR for one 1-ton AC or a group of home electronics. Multi-tap relay switching gives quick, steady correction across a wide input range. Built-in over/under-voltage cutoff and time-delay restart protect the compressor. It has a steel cabinet, an LED voltage display, and the same Lahore-backed warranty as our other products.",
    image: "assets/prod-avr.jpg",
    specs: [
      ["Technology", "AVR — relay tap-switching"],
      ["Capacity", "3kVA, single-phase"],
      ["Input range", "140V – 270V AC"],
      ["Output", "220V ±5%"],
      ["Response time", "< 1 second"],
      ["Protection", "OV/UV cutoff, delay restart"],
      ["Display", "LED voltage meter"],
    ],
  },

  // ===== INDUSTRIAL STABILIZERS =====
  {
    id: "vt-ind-100k",
    name: "Industrial Stabilizer — 100kVA",
    category: "Industrial Stabilizers",
    categoryId: "industrial",
    tech: "SVC",
    badge: "Industrial",
    tagline: "3-phase servo stabilizer for factories, mills, and commercial buildings.",
    highlight: ["100kVA", "3-phase"],
    description:
      "Built for plants that cannot lose a single shift. This 100kVA three-phase servo stabilizer fixes each phase on its own. So unbalanced WAPDA supply becomes clean, balanced 400V at the output. It has heavy copper windings, large contactors, forced-air cooling, and a thermal-protected controller rated for 50°C non-stop. It runs in textile and food plants across Punjab.",
    image: "assets/prod-3phase.png",
    specs: [
      ["Technology", "SVC — 3-phase servo"],
      ["Capacity", "100kVA, 3-phase"],
      ["Input range", "300V – 460V (L-L)"],
      ["Output", "400V ±1%"],
      ["Correction speed", "35V / second"],
      ["Efficiency", "> 97%"],
      ["Ambient rating", "50°C continuous"],
      ["Cooling", "Forced air, thermal cutoff"],
    ],
  },
  {
    id: "vt-ind-200k",
    name: "Industrial Stabilizer — 200kVA",
    category: "Industrial Stabilizers",
    categoryId: "industrial",
    tech: "SVC",
    badge: "Heavy duty",
    tagline: "Heavy industrial servo stabilizer — the one running K&N's lines.",
    highlight: ["200kVA", "50°C rated"],
    description:
      "Built for factories that cannot lose a single shift. Three separate servo motors move variable autotransformers, one per phase, to fix voltage at 35V per second. It has heavy copper windings, large contactors, and a thermal-protected control board that runs 24/7 in 50°C heat. It runs at K&N's, Fauji Fertilizer, and dozens of textile mills across Punjab.",
    image: "assets/prod-3phase.png",
    specs: [
      ["Technology", "SVC — 3-phase servo"],
      ["Capacity", "200kVA, 3-phase"],
      ["Input range", "280V – 480V (L-L)"],
      ["Output", "400V ±1%"],
      ["Correction speed", "35V / second"],
      ["Efficiency", "> 97%"],
      ["Ambient rating", "50°C continuous"],
      ["Cooling", "Forced air, thermal cutoff"],
    ],
  },
  {
    id: "vt-ind-igbt-100k",
    name: "Industrial IGBT Stabilizer — 100kVA",
    category: "Industrial Stabilizers",
    categoryId: "industrial",
    tech: "IGBT",
    badge: "Zero maintenance",
    tagline: "Static 3-phase IGBT stabilizer — no servos to service across three shifts.",
    highlight: ["< 20ms", "no moving parts"],
    description:
      "When uptime matters most, take out the moving parts. This 100kVA three-phase IGBT static stabilizer fixes all three phases in milliseconds. There are no servo motors, no carbon brushes, and no maintenance shutdowns. Best for precision factories, data rooms, and medical sites where servo lag or downtime is not acceptable.",
    image: "assets/prod-industrial.jpg",
    specs: [
      ["Technology", "IGBT static, 3-phase"],
      ["Capacity", "100kVA, 3-phase"],
      ["Input range", "300V – 460V (L-L)"],
      ["Output", "400V ±1%"],
      ["Correction speed", "< 20 ms (electronic)"],
      ["Efficiency", "> 98%"],
      ["Maintenance", "Zero — no brushes or motor"],
      ["Cooling", "Forced air, redundant fans"],
    ],
  },
  {
    id: "vt-ind-500k",
    name: "Industrial Stabilizer — 500kVA",
    category: "Industrial Stabilizers",
    categoryId: "industrial",
    tech: "SVC",
    tagline: "Half-megawatt servo stabilizer that fixes very low voltage.",
    highlight: ["500kVA", "oil-cooled"],
    description:
      "When your factory pulls half a megawatt and the input voltage swings 200V on a hot afternoon, this keeps you running. It is a forced-oil-cooled three-phase servo stabilizer that fixes very low voltage down to 260V L-L. It has heavy copper, thermostatic monitoring, and a control system that has run non-stop in textile mills, cold stores, and dairy plants across Pakistan for over 15 years. Custom builds on request.",
    image: "assets/prod-industrial.jpg",
    specs: [
      ["Technology", "SVC — 3-phase servo"],
      ["Capacity", "500kVA, 3-phase"],
      ["Input range", "260V – 480V (L-L)"],
      ["Output", "400V ±1%"],
      ["Correction speed", "45V / second"],
      ["Efficiency", "> 97.5%"],
      ["Cooling", "Forced oil, thermostatic"],
      ["Ambient rating", "50°C continuous"],
    ],
  },

  // ===== LITHIUM CELLS =====
  {
    id: "vt-eve-lf100",
    name: "EVE LF100 — 3.2V 100Ah LFP Cell",
    category: "Lithium Cells",
    categoryId: "cells",
    tech: "LFP",
    badge: "Most shipped",
    tagline: "Genuine EVE Grade-A 100Ah prismatic cell — our most-shipped product.",
    highlight: ["6,000+", "cycles"],
    cell: {
      format: "Prismatic LFP",
      capacityAh: "100",
      voltageV: "3.2",
      cycles: "6,000+",
      weight: "2.0 kg",
      size: "174 × 72 × 207 mm",
      cRate: "0.5C / 0.5C",
      applications: ["Home solar storage", "Telecom & base stations", "UPS & backup", "Commercial ESS"],
      features: ["High energy density", "6,000+ cycle life", "High safety (LFP)", "Low internal resistance", "Grade-A matched", "Full life cycle"],
      certifications: ["ISO 9001", "CE", "UN38.3", "RoHS", "REACH", "UL", "IEC"],
    },
    description:
      "Genuine EVE Grade-A prismatic LFP — direct from the factory, never grade-B. The cell behind most home solar banks in Pakistan.",
    image: "assets/prod-lithium.png",
    specs: [
      ["Chemistry", "LiFePO4 (LFP)"],
      ["Nominal voltage", "3.2V"],
      ["Capacity", "100Ah at 0.5C, 25°C"],
      ["Cycle life", "6,000+ at 80% DoD"],
      ["Operating temp", "-20°C to +55°C"],
      ["Internal resistance", "< 0.5 mΩ"],
      ["Dimensions", "174 × 72 × 207 mm"],
      ["Weight", "2.0 kg"],
      ["Origin", "EVE Energy, China"],
      ["Warranty", "5 years prorated"],
    ],
  },
  {
    id: "vt-eve-lf280k",
    name: "EVE LF280K — 3.2V 280Ah LFP Cell",
    category: "Lithium Cells",
    categoryId: "cells",
    tech: "LFP",
    tagline: "The cell for big solar storage and EV pack builds.",
    highlight: ["280Ah", "14kWh / 16 cells"],
    cell: {
      format: "Prismatic LFP",
      capacityAh: "280",
      voltageV: "3.2",
      cycles: "6,000+",
      weight: "5.4 kg",
      size: "174 × 72 × 207 mm",
      cRate: "0.5C / 0.5C",
      applications: ["Home & whole-home solar", "Commercial ESS", "EV pack builds", "Off-grid systems"],
      features: ["High energy density", "6,000+ cycle life", "High safety (LFP)", "Low internal resistance", "Grade-A matched", "Full life cycle"],
      certifications: ["ISO 9001", "CE", "UN38.3", "RoHS", "REACH", "UL", "IEC"],
    },
    description:
      "280Ah of genuine EVE Grade-A LFP. Sixteen cells make a 14kWh / 48V bank — enough to run a whole home through load-shedding.",
    image: "assets/prod-lithium.png",
    specs: [
      ["Chemistry", "LiFePO4 (LFP)"],
      ["Nominal voltage", "3.2V"],
      ["Capacity", "280Ah at 0.5C, 25°C"],
      ["Cycle life", "6,000+ at 80% DoD"],
      ["Operating temp", "-20°C to +55°C"],
      ["Internal resistance", "< 0.25 mΩ"],
      ["Dimensions", "174 × 72 × 207 mm"],
      ["Weight", "5.4 kg"],
      ["Origin", "EVE Energy, China"],
      ["Warranty", "5 years prorated"],
    ],
  },
  {
    id: "vt-eve-lf304",
    name: "EVE LF304 — 3.2V 304Ah LFP Cell",
    category: "Lithium Cells",
    categoryId: "cells",
    tech: "LFP",
    tagline: "Our highest-capacity prismatic cell for dense storage banks.",
    highlight: ["304Ah", "highest density"],
    cell: {
      format: "Prismatic LFP",
      capacityAh: "304",
      voltageV: "3.2",
      cycles: "6,000+",
      weight: "5.6 kg",
      size: "174 × 72 × 207 mm",
      cRate: "0.5C / 0.5C",
      applications: ["Commercial & industrial ESS", "Telecom towers", "Whole-home solar", "Grid storage"],
      features: ["Highest energy density", "6,000+ cycle life", "High safety (LFP)", "Lowest internal resistance", "Grade-A matched", "Fewer interconnects"],
      certifications: ["ISO 9001", "CE", "UN38.3", "RoHS", "REACH", "UL", "IEC"],
    },
    description:
      "Our highest-capacity prismatic cell. 304Ah of genuine EVE Grade-A LFP — more storage per cabinet, lower cost per kWh. Best for commercial ESS.",
    image: "assets/prod-lithium.png",
    specs: [
      ["Chemistry", "LiFePO4 (LFP)"],
      ["Nominal voltage", "3.2V"],
      ["Capacity", "304Ah at 0.5C, 25°C"],
      ["Cycle life", "6,000+ at 80% DoD"],
      ["Operating temp", "-20°C to +55°C"],
      ["Internal resistance", "< 0.22 mΩ"],
      ["Dimensions", "174 × 72 × 207 mm"],
      ["Weight", "5.6 kg"],
      ["Origin", "EVE Energy, China"],
      ["Warranty", "5 years prorated"],
    ],
  },
  {
    id: "vt-eve-40135",
    name: "EVE Cylindrical 40135 — 15Ah LFP",
    category: "Lithium Cells",
    categoryId: "cells",
    tech: "LFP",
    status: "upcoming",
    badge: "Coming soon",
    tagline: "Large cylindrical LFP — arriving Q3 2026 for modular packs.",
    highlight: ["Q3 2026", "register interest"],
    cell: {
      format: "Cylindrical LFP",
      capacityAh: "15",
      voltageV: "3.2",
      cycles: "4,000+",
      weight: "—",
      size: "40 × 135 mm",
      cRate: "1C / 1C",
      applications: ["Light EVs & e-bikes", "Modular packs", "Small storage", "Power tools"],
      features: ["Thermally stable", "Easy module assembly", "High safety (LFP)", "Robust weldable can", "Fast charging", "Long life"],
      certifications: ["ISO 9001", "CE", "UN38.3", "RoHS", "REACH"],
    },
    description:
      "Large cylindrical LFP for light EVs, e-bikes and modular packs. Genuine EVE — arriving Q3 2026. Join the pre-order list for launch pricing.",
    image: "assets/prod-cylindrical.jpg",
    specs: [
      ["Chemistry", "LiFePO4 (LFP)"],
      ["Format", "Cylindrical 40135"],
      ["Nominal voltage", "3.2V"],
      ["Capacity", "15Ah (typical)"],
      ["Cycle life", "4,000+ at 80% DoD"],
      ["Status", "Arriving Q3 2026"],
      ["Origin", "EVE Energy, China"],
      ["Availability", "Pre-order open"],
    ],
  },
  {
    id: "vt-eve-46105",
    name: "EVE Cylindrical 46105 — 32Ah LFP",
    category: "Lithium Cells",
    categoryId: "cells",
    tech: "LFP",
    status: "upcoming",
    badge: "Coming soon",
    tagline: "New 46-series cylindrical cell for EV and high-power packs.",
    highlight: ["Q4 2026", "register interest"],
    cell: {
      format: "Cylindrical LFP",
      capacityAh: "32",
      voltageV: "3.2",
      cycles: "4,000+",
      weight: "—",
      size: "46 × 105 mm",
      cRate: "1C / 1C",
      applications: ["Electric 2 & 3-wheelers", "High-power packs", "Fast-charge EVs", "Modular storage"],
      features: ["High power density", "Fast charging", "High safety (LFP)", "Robust weldable can", "Industry-standard 46 format", "Long life"],
      certifications: ["ISO 9001", "CE", "UN38.3", "RoHS", "REACH"],
    },
    description:
      "Next-gen 46-series cylindrical cell for EVs and high-power packs. Genuine EVE — arriving Q4 2026. Join the pre-order list for launch stock.",
    image: "assets/prod-cylindrical.jpg",
    specs: [
      ["Chemistry", "LiFePO4 (LFP)"],
      ["Format", "Cylindrical 46105"],
      ["Nominal voltage", "3.2V"],
      ["Capacity", "32Ah (typical)"],
      ["Cycle life", "4,000+ at 80% DoD"],
      ["Status", "Arriving Q4 2026"],
      ["Origin", "EVE Energy, China"],
      ["Availability", "Pre-order open"],
    ],
  },

  // ===== ELECTRIC PARTS (BMS, relays, LED displays) =====
  {
    id: "vt-bms-16s",
    name: "DALY BMS — 16S 100A Active Balancing",
    category: "Electric Parts",
    categoryId: "parts",
    tech: "BMS",
    hidden: true,
    tagline: "16-series LFP protection with active balancing and CAN for inverters.",
    highlight: ["16S", "CAN-ready"],
    description:
      "The control board that turns 16 cells into a real battery. This DALY active-balancing BMS keeps every cell within 5mV of the others, even after years of use. CAN protocols let it talk to Victron, Deye, SRNE, and Growatt inverters right out of the box. It ships with our tested firmware and a 72-hour bench test report — not generic AliExpress firmware.",
    image: "assets/prod-bms.png",
    specs: [
      ["Configuration", "16S (48V nominal LFP)"],
      ["Continuous current", "100A"],
      ["Peak current", "200A for 10s"],
      ["Balancing", "Active, 2A capacitor bridge"],
      ["Communication", "UART, RS485, CAN 2.0B"],
      ["Inverter protocols", "Victron, Deye, SRNE, Growatt"],
      ["Dimensions", "195 × 120 × 32 mm"],
    ],
  },
  {
    id: "vt-relay-t73",
    name: "Wirell T73 PCB Relay — 5A/7A/10A",
    category: "Electric Parts",
    categoryId: "parts",
    tech: "Relay",
    tagline: "Compact PCB power relay (JQC-3F) for control boards — up to 10A.",
    highlight: ["T73", "up to 10A"],
    description:
      "The small power relay every control board needs — Wirell's JQC-3F (T73). Silver-alloy contacts switch up to 10A, with a 99% pure-copper coil for a long, reliable life. Built for stabilizer controllers, inverters, solar charge controllers and automation panels. Standard PCB through-hole footprint. Stocked by the thousand for next-day dispatch.",
    image: "assets/prod-relay.jpg",
    specs: [
      ["Model", "Wirell JQC-3F (T73)"],
      ["Contact rating", "7A @ 250VAC · 10A @ 125VAC · 5A @ 30VDC"],
      ["Max switching power", "1750VA / 120W"],
      ["Contact material", "Silver alloy"],
      ["Coil", "Pure copper (99%)"],
      ["Operate / release time", "≤ 10ms / ≤ 5ms"],
      ["Electrical life", "100,000+ cycles"],
      ["Mechanical life", "2,000,000+ cycles"],
      ["Insulation", "500MΩ · 750VAC / 1 min"],
      ["Mounting", "PCB through-hole"],
      ["Operating temp", "-25°C to +55°C"],
    ],
  },
  {
    id: "vt-relay-t90",
    name: "Wirell T90 PCB Relay — 20A/30A/40A",
    category: "Electric Parts",
    categoryId: "parts",
    tech: "Relay",
    tagline: "Heavy-duty PCB power relay (JQX-15F) for high-current switching — up to 40A.",
    highlight: ["T90", "up to 40A"],
    description:
      "Wirell's JQX-15F (T90) is the heavy-duty PCB relay for high-current switching — up to 40A. Available in 1A, 1B and 1C contact forms with silver-alloy contacts that take real motor and inrush loads. The switching heart of AVR stabilizers, inverters and power panels. Standard PCB through-hole footprint. Stocked by the thousand for next-day dispatch.",
    image: "assets/prod-relay.jpg",
    specs: [
      ["Model", "Wirell JQX-15F (T90)"],
      ["Contact rating", "20A / 30A / 40A"],
      ["Max switching capacity", "30A @ 250VAC / 30VDC"],
      ["Switching power", "AC 7500VA / 900W · DC 5000VA / 600W"],
      ["Contact form", "1A / 1B / 1C"],
      ["Contact material", "Silver alloy"],
      ["Coil power", "0.9W (DC) · 12VA (AC)"],
      ["Operate / release time", "< 15ms / < 10ms"],
      ["Electrical life", "100,000+ cycles"],
      ["Mechanical life", "2,000,000+ cycles"],
      ["Insulation", "500MΩ · 1500VAC / 1 min"],
      ["Mounting", "PCB through-hole"],
      ["Operating temp", "-40°C to +70°C"],
    ],
  },
  {
    id: "vt-led-5630",
    name: "7-Segment LED Display — 5630",
    category: "Electric Parts",
    categoryId: "parts",
    tech: "LED",
    tagline: "Bright 7-segment display module for stabilizer and meter panels.",
    highlight: ["5630", "7-segment"],
    description:
      "PLACEHOLDER LISTING — full specs still to be confirmed. A 5630-series 7-segment LED display module for stabilizer fronts, panel meters, and instruments. Bright segments with a wide viewing angle. Supplied to makers and repair workshops across Pakistan.",
    image: "assets/prod-relay.jpg",
    specs: [
      ["Type", "7-segment LED display"],
      ["Series", "5630"],
      ["Colour", "Red (others on request)"],
      ["Application", "Stabilizer / meter panels"],
      ["Warranty", "Manufacturer defect"],
    ],
  },
  {
    id: "vt-led-4630",
    name: "7-Segment LED Display — 4630",
    category: "Electric Parts",
    categoryId: "parts",
    tech: "LED",
    tagline: "Small 7-segment display module for instrument and control panels.",
    highlight: ["4630", "7-segment"],
    description:
      "PLACEHOLDER LISTING — full specs still to be confirmed. A 4630-series 7-segment LED display module for small instrument readouts and control panels. Bright, even segments give clear voltage and load readouts. Stocked at our Lahore warehouse.",
    image: "assets/prod-relay.jpg",
    specs: [
      ["Type", "7-segment LED display"],
      ["Series", "4630"],
      ["Colour", "Red (others on request)"],
      ["Application", "Instrument / control panels"],
      ["Warranty", "Manufacturer defect"],
    ],
  },
];

export const CATEGORIES: Category[] = [
  { id: "all", label: "All products", count: 24 },
  { id: "stabilizers", label: "Stabilizers", count: 11 },
  { id: "cells", label: "Lithium Cells", count: 5 },
  { id: "industrial", label: "Industrial", count: 4 },
  { id: "parts", label: "Electric Parts", count: 4 },
];

export function getProduct(id: string): Product | undefined {
  return PRODUCTS.find((p) => p.id === id);
}

export function relatedProducts(p: Product, limit = 3): Product[] {
  return PRODUCTS.filter(
    (x) => x.id !== p.id && x.categoryId === p.categoryId,
  ).slice(0, limit);
}
